import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react'
import { Activity, BatteryCharging, Bot, Boxes, ChevronRight, Clock3, Cpu, Gauge, MapPin, Network, PackageCheck, Pause, Play, Plus, Radar, RefreshCcw, ShieldCheck, TriangleAlert, Truck, Zap, type LucideIcon } from 'lucide-react'
import { initialRobots, points, storageRacks } from './data'
import type { Log, Metrics, Point, Robot, Task } from './types'

const now = () => new Date().toLocaleTimeString([], { hour12: false })
const distance = (a: Point, b: Point) => Math.hypot(a.x - b.x, a.y - b.y)
const pathBetween = (_from: Point, to: Point, _avoidBlocked = false): Point[] => [to]
const sidestepRoute = (from: Point, to: Point, direction: 1 | -1): Point[] => {
  const routeLength = Math.max(distance(from, to), 1)
  const sideways = { x: -(to.y - from.y) / routeLength * 11 * direction, y: (to.x - from.x) / routeLength * 11 * direction }
  const waypoint = { x: Math.max(5, Math.min(95, from.x + sideways.x)), y: Math.max(5, Math.min(93, from.y + sideways.y)) }
  return [waypoint, to]
}
const makeTask = (id: number): Task => { const source = storageRacks[(id * 3 + 2) % storageRacks.length]; return { id: `TASK-${String(id).padStart(3,'0')}`, source, destination: 'Dispatch', item: `Box-${100 + id * 7}`, priority: id % 3 === 0 ? 'HIGH' : 'NORMAL', status: 'PENDING', createdAt: Date.now(), phase: 0 } }

function App() {
  const [robots, setRobots] = useState<Robot[]>(initialRobots)
  const [tasks, setTasks] = useState<Task[]>([])
  const [metrics, setMetrics] = useState<Metrics>({ picked: 0, packed: 0, dispatched: 0, reroutes: 0, prevented: 0, energy: 0 })
  const [logs, setLogs] = useState<Log[]>([])
  const [running, setRunning] = useState(false)
  const [demo, setDemo] = useState(false)
  const [speed, setSpeed] = useState(1)
  const [selected, setSelected] = useState<string>('R1')
  const [blocked, setBlocked] = useState(false)
  const [decision, setDecision] = useState('Awaiting local telemetry')
  const taskCounter = useRef(0); const lastTick = useRef(performance.now()); const lastTask = useRef(0); const conflictDone = useRef(false)
  const log = useCallback((type: Log['type'], message: string) => setLogs(old => [{ time: now(), type, message }, ...old].slice(0, 40)), [])
  const createTask = useCallback(() => { if (tasks.filter(t => t.status === 'PENDING').length >= 10) return; taskCounter.current += 1; const task = makeTask(taskCounter.current); setTasks(old => [...old, task]); log('INFO', `${task.id} created · ${task.source} → Dispatch`); }, [log, tasks])
  const startSimulation = () => { setRunning(true); if (!tasks.some(task => task.status !== 'COMPLETED')) createTask() }
  const reset = () => { setRunning(false); setDemo(false); setRobots(initialRobots()); setTasks([]); setMetrics({picked:0,packed:0,dispatched:0,reroutes:0,prevented:0,energy:0}); setLogs([]); setBlocked(false); setDecision('Awaiting local telemetry'); taskCounter.current = 0; conflictDone.current = false }
  const assign = useCallback((allRobots: Robot[], allTasks: Task[]) => {
    const pending = allTasks.find(t => t.status === 'PENDING'); if (!pending) return { robots: allRobots, tasks: allTasks }
    const ranked = allRobots.filter(r => r.status === 'IDLE' && r.battery > 20).map(r => ({ r, score: distance(r.position, points[pending.source]) + r.completed * 8 + (100-r.battery)*.25 })).sort((a,b)=>a.score-b.score)
    if (!ranked.length) return { robots: allRobots, tasks: allTasks }
    const chosen = ranked[0].r; const route = pathBetween(chosen.position, points[pending.source]);
    log('EDGE AI', `${pending.id} → ${chosen.id} · nearest available edge node`); setDecision(`${chosen.id} selected ${pending.id}: nearest available robot with sufficient battery`)
    return { robots: allRobots.map(r => r.id === chosen.id ? {...r, status:'MOVING' as const, taskId:pending.id, route, routeIndex:0} : r), tasks: allTasks.map(t => t.id === pending.id ? {...t, robotId:chosen.id, status:'IN PROGRESS' as const, startedAt:Date.now()} : t) }
  }, [log])
  useEffect(() => {
    let frame = 0
    const tick = (time: number) => { const elapsed = Math.min((time-lastTick.current)/1000, .08) * speed; lastTick.current = time
      if (running) {
        if (demo && time-lastTask.current > 3800/speed && tasks.filter(t=>t.status==='PENDING').length < 4) { lastTask.current=time; createTask() }
        setRobots(previous => { let next = previous.map(r => ({...r, position:{...r.position}})); let nextTasks = tasks.map(t=>({...t})); let addedMetrics: Partial<Metrics> = {}; let changes: Log[] = []
          next.forEach(robot => {
            if (robot.status === 'CHARGING') { robot.battery = Math.min(100, robot.battery + elapsed * 7); if (robot.battery > 82) { robot.status='IDLE'; robot.charging=false; changes.push({time:now(),type:'SUCCESS',message:`${robot.id} charged and available`}) } return }
            if (!robot.route.length || robot.status === 'WAITING') { if (robot.status === 'WAITING') { robot.waiting -= elapsed; if (robot.waiting <= 0) { robot.status='REROUTING'; robot.route = sidestepRoute(robot.position, robot.holdTarget || points.Packing, robot.id === 'R1' || robot.id === 'R3' || robot.id === 'R5' ? 1 : -1); robot.routeIndex=0; robot.holdTarget=undefined; changes.push({time:now(),type:'EDGE AI',message:`${robot.id} turned aside and resumed on a collision-free vector`}) } } return }
            const target = robot.route[robot.routeIndex]; const gap = distance(robot.position, target); const step = elapsed * 11
            if (gap <= step) { robot.position = {...target}; robot.routeIndex++; if (robot.routeIndex >= robot.route.length) { robot.route=[]; const task=nextTasks.find(t=>t.id===robot.taskId); if (!task) { if (robot.charging) { robot.status='CHARGING'; changes.push({time:now(),type:'INFO',message:`${robot.id} docked at charging station`}) } return } if (task.phase===0) { task.phase=1; robot.status='TRANSPORTING'; robot.items=1; addedMetrics.picked=(addedMetrics.picked||0)+1; robot.route=pathBetween(robot.position,points.Packing,blocked); robot.routeIndex=0; changes.push({time:now(),type:'SUCCESS',message:`${robot.id} picked ${task.item} at ${task.source}`}) } else if (task.phase===1) { task.phase=2; robot.status='TRANSPORTING'; addedMetrics.packed=(addedMetrics.packed||0)+1; robot.route=pathBetween(robot.position,points.Dispatch,blocked); robot.routeIndex=0; changes.push({time:now(),type:'SUCCESS',message:`${task.item} packed · ${robot.id} heading to dispatch`}) } else { task.phase=3; task.status='COMPLETED'; task.completedAt=Date.now(); robot.status='IDLE'; robot.items=0; robot.completed++; robot.taskId=undefined; addedMetrics.dispatched=(addedMetrics.dispatched||0)+1; changes.push({time:now(),type:'SUCCESS',message:`${task.id} completed · dispatched by ${robot.id}`}); return } }
            } else { const dx=(target.x-robot.position.x)/gap, dy=(target.y-robot.position.y)/gap; robot.position.x+=dx*step; robot.position.y+=dy*step; robot.distance += step; robot.battery=Math.max(0,robot.battery-step*.08); addedMetrics.energy=(addedMetrics.energy||0)+step*.08 }
          })
          const activeRobots = next.filter(robot => ['MOVING', 'TRANSPORTING', 'REROUTING'].includes(robot.status) && robot.route.length)
          for (let firstIndex = 0; firstIndex < activeRobots.length; firstIndex += 1) for (let secondIndex = firstIndex + 1; secondIndex < activeRobots.length; secondIndex += 1) { const first = activeRobots[firstIndex], second = activeRobots[secondIndex]; const firstTarget = first.route[first.routeIndex], secondTarget = second.route[second.routeIndex]; const sameDestination = distance(firstTarget, secondTarget) < 2.5; const robotSeparation = distance(first.position, second.position); const unsafeDistance = robotSeparation < 8; if (unsafeDistance || (sameDestination && robotSeparation < 20)) { const yieldingRobot = first.id > second.id ? first : second; const continuingRobot = yieldingRobot === first ? second : first; yieldingRobot.holdTarget = yieldingRobot.route.at(-1); yieldingRobot.route=[]; yieldingRobot.routeIndex=0; yieldingRobot.status='WAITING'; yieldingRobot.waiting=.7; addedMetrics.prevented=(addedMetrics.prevented||0)+1; addedMetrics.reroutes=(addedMetrics.reroutes||0)+1; changes.push({time:now(),type:'SAFETY',message:`Safety radius ${robotSeparation.toFixed(1)} m: ${yieldingRobot.id} yielded to ${continuingRobot.id}`}); changes.push({time:now(),type:'EDGE AI',message:`${yieldingRobot.id} executing visible side-step turn around local traffic`}); setDecision(`${yieldingRobot.id} measured ${robotSeparation.toFixed(1)} m to ${continuingRobot.id}; yielding and steering around it.`); break } }
          const allocated=assign(next,nextTasks); next=allocated.robots; nextTasks=allocated.tasks; if(changes.length) setLogs(old=>[...changes.reverse(),...old].slice(0,40)); if(Object.keys(addedMetrics).length) setMetrics(m=>({...m, ...Object.fromEntries(Object.entries(addedMetrics).map(([k,v])=>[k,(m[k as keyof Metrics]||0)+(v||0)]))})); setTasks(nextTasks); return next
        })
      }
      frame=requestAnimationFrame(tick)
    }; frame=requestAnimationFrame(tick); return () => cancelAnimationFrame(frame)
  }, [running, speed, demo, tasks, blocked, createTask, assign])
  const completed=tasks.filter(t=>t.status==='COMPLETED').length, active=tasks.filter(t=>t.status==='IN PROGRESS').length, pending=tasks.filter(t=>t.status==='PENDING').length
  const avgTime=completed ? Math.round(tasks.filter(t=>t.completedAt&&t.startedAt).reduce((total,t)=>total+(t.completedAt!-t.startedAt!)/1000,0)/completed) : 0
  const avgBattery=Math.round(robots.reduce((sum,r)=>sum+r.battery,0)/robots.length), moving=robots.filter(r=>!['IDLE','CHARGING','WAITING'].includes(r.status)).length, totalDistance=robots.reduce((sum,r)=>sum+r.distance,0)
  const selectedRobot=robots.find(r=>r.id===selected)!
  const cards: Array<[string, string | number, LucideIcon, string]>=[['Completed',completed,PackageCheck,'success'],['Active Tasks',active,Activity,'cyan'],['Pending',pending,Clock3,'muted'],['Items Picked',metrics.picked,Boxes,'blue'],['Items Packed',metrics.packed,PackageCheck,'violet'],['Dispatched',metrics.dispatched,Truck,'success'],['Collisions',0,ShieldCheck,'success'],['Prevented',metrics.prevented,ShieldCheck,'orange'],['Re-routes',metrics.reroutes,RefreshCcw,'orange'],['Distance',`${totalDistance.toFixed(1)} m`,MapPin,'cyan'],['Energy Used',`${metrics.energy.toFixed(1)}%`,Zap,'orange'],['Avg Task',`${avgTime} sec`,Gauge,'muted']]
  return <main>
    <header><div className="brand"><div className="brand-mark"><Bot size={23}/></div><div><h1>SMART WAREHOUSE</h1><p>Edge-AI Distributed AMR Fleet Coordination</p></div></div><div className="header-status"><span className="online"><i/> SYSTEM ONLINE</span><span><Cpu size={15}/> EDGE AI: <b>ACTIVE</b></span><span><Network size={15}/> AMR FLEET: <b>5 ONLINE</b></span><span className="clock"><Clock3 size={15}/>{now()}</span></div></header>
    <section className="kpis">{cards.map(([label,value,Icon,tone])=>{const C=Icon as typeof Activity; return <article className={`kpi ${tone}`} key={String(label)}><C size={16}/><span>{label}</span><strong>{value as string|number}</strong></article>})}</section>
    <section className="workspace"><div className="simulation-shell"><div className="map-top"><div><span className="eyebrow">LIVE DIGITAL TWIN</span><h2>Warehouse Operations Map</h2></div><div className="map-tags"><span><i/> Navigation graph online</span>{blocked&&<span className="alert">⚠ R21 BLOCKED</span>}</div></div><Warehouse robots={robots} selected={selected} onSelect={setSelected} blocked={blocked}/><FleetBatteries robots={robots}/></div>
      <aside className="right-rail"><Decision decision={decision}/><RobotDetail robot={selectedRobot} task={tasks.find(t=>t.id===selectedRobot.taskId)}/><NetworkPanel robots={robots}/></aside></section>
    <section className="lower"><div className="panel controls"><PanelTitle icon={<Radar size={17}/>} title="Simulation Control"/><div className="control-buttons"><button className="primary" onClick={startSimulation}><Play size={15}/> Start Simulation</button><button onClick={()=>setRunning(false)}><Pause size={15}/> Pause</button><button onClick={reset}><RefreshCcw size={15}/> Reset</button><button onClick={createTask}><Plus size={15}/> Generate Task</button><button onClick={()=>{setBlocked(true);setMetrics(m=>({...m,reroutes:m.reroutes+robots.filter(r=>r.route.length>0).length}));log('WARNING','Aisle R21 temporarily blocked · active routes recalculated');setDecision('R21 obstacle broadcast to nearby edge nodes. Alternate routes enabled.')}}><TriangleAlert size={15}/> Obstacle</button><button onClick={()=>{conflictDone.current=false;setDecision('High traffic simulated near the Central Aisle. Local safety radius increased.');log('SAFETY','High traffic alert · decentralized yield protocol armed')}}><Activity size={15}/> High Traffic</button><button onClick={()=>{const candidate=robots.find(r=>r.status==='IDLE')||robots[0];setRobots(rs=>rs.map(r=>r.id===candidate.id?{...r,battery:18,status:'MOVING',charging:true,route:pathBetween(r.position,points.Charging),routeIndex:0}:r));log('WARNING',`${candidate.id} battery at 18% · routing to charging station`);setDecision(`${candidate.id}: low battery event. Local controller reserved a charging dock.`)}}><BatteryCharging size={15}/> Low Battery</button></div><div className="speed"><span>SIMULATION SPEED</span>{[.5,1,2,4].map(n=><button key={n} className={speed===n?'selected':''} onClick={()=>setSpeed(n)}>{n}x</button>)}<button className={`demo ${demo?'active':''}`} onClick={()=>{setDemo(true);startSimulation();log('EDGE AI','Demo Mode Active · autonomous workflow initiated')}}><Zap size={15}/> {demo?'DEMO MODE ACTIVE':'START DEMO MODE'}</button></div></div>
      <TaskTable tasks={tasks}/><ActivityLog logs={logs}/><EdgePanel robots={robots} moving={moving} avgBattery={avgBattery}/></section>
  </main>
}

function PanelTitle({icon,title}:{icon:ReactNode;title:string}) { return <h3 className="panel-title">{icon}{title}</h3> }
function FleetBatteries({robots}:{robots:Robot[]}) { return <div className="fleet-batteries"><span>FLEET BATTERY</span>{robots.map(robot=><div key={robot.id} className="fleet-battery"><i style={{background:robot.color}}/>{robot.id}<b>{Math.round(robot.battery)}%</b><em><u style={{width:`${robot.battery}%`,background:robot.battery < 20 ? '#fb923c' : robot.color}}/></em></div>)}</div> }
function Warehouse({robots,selected,onSelect,blocked}:{robots:Robot[];selected:string;onSelect:(id:string)=>void;blocked:boolean}) { const racks=storageRacks; return <div className="warehouse"><div className="zone pickup"><b>PICKUP / STORAGE</b><span>Inbound pallets</span><Boxes size={23}/></div><div className="zone packing"><b>PACKING AREA</b><span>Sort · seal · label</span><PackageCheck size={23}/></div><div className="zone dispatch"><b>DISPATCH / LOADING</b><span>Outbound bay</span><Truck size={24}/></div><div className="zone edge"><Cpu size={18}/><b>EDGE CONTROL</b><span>Local mesh</span></div><div className="zone charging"><BatteryCharging size={18}/><b>ROBOT CHARGING</b><span>05 docks</span></div><div className="zone maintenance"><Gauge size={16}/><b>MAINTENANCE</b></div><div className="aisle-label">CENTRAL NAVIGATION AISLE</div><div className="racks">{racks.map(rack=><div className={`rack ${rack==='R21'&&blocked?'blocked':''}`} key={rack}><span>{rack}</span><i/><i/><i/><i/>{rack==='R21'&&<em>BLOCKED</em>}</div>)}</div><svg className="routes" viewBox="0 0 100 100" preserveAspectRatio="none">{robots.filter(r=>r.route.length).map(r=> <polyline key={r.id} points={[r.position,...r.route.slice(r.routeIndex)].map(p=>`${p.x},${p.y}`).join(' ')} stroke={r.color} />)}</svg>{robots.map(robot=><button aria-label={robot.id} key={robot.id} className={`robot ${selected===robot.id?'active':''} ${robot.status.toLowerCase()}`} style={{left:`${robot.position.x}%`,top:`${robot.position.y}%`, '--robot':robot.color} as React.CSSProperties} onClick={()=>onSelect(robot.id)}><span className="arrow">▲</span><b>{robot.id}</b><i/></button>)}<div className="floor-lines"/></div> }
function Decision({decision}:{decision:string}) { return <div className="panel decision"><PanelTitle icon={<Cpu size={17}/>} title="Edge AI Decision"/><p>{decision}</p><small><span/> DECENTRALIZED LOCAL INFERENCE</small></div> }
function RobotDetail({robot,task}:{robot:Robot;task?:Task}) { return <div className="panel robot-detail"><PanelTitle icon={<Bot size={17}/>} title={`${robot.id} · Edge Node`}/><div className="robot-state"><span style={{background:robot.color}}/><b>{robot.status}</b><small>{task?.id||'AVAILABLE'}</small></div><div className="detail-grid"><label>Location <b>{task?.source || 'Navigation aisle'}</b></label><label>Destination <b>{task?.phase===2?'Dispatch Area':task?'Packing Area':'Available'}</b></label><label>Speed <b>{robot.status==='IDLE'?'0.0':'1.2'} m/s</b></label><label>Distance <b>{robot.distance.toFixed(1)} m</b></label><label>Items <b>{robot.items}</b></label><label>Completed <b>{robot.completed}</b></label></div><div className="battery"><span>BATTERY <b>{Math.round(robot.battery)}%</b></span><div><i style={{width:`${robot.battery}%`}}/></div></div></div> }
function NetworkPanel({robots}:{robots:Robot[]}) { return <div className="panel network"><PanelTitle icon={<Network size={17}/>} title="Robot Network"/><div><b>CONNECTED ROBOTS</b><strong>5/5</strong></div><div><b>MESSAGES / SEC</b><strong>{robots.some(r=>r.status!=='IDLE')?'12':'0'}</strong></div><p><span/> LOCAL COMMUNICATION ACTIVE</p></div> }
function TaskTable({tasks}:{tasks:Task[]}) { return <div className="panel task-table"><PanelTitle icon={<Boxes size={17}/>} title="Live Task Queue"/><div className="table-head"><span>TASK ID</span><span>ROBOT</span><span>SOURCE → DESTINATION</span><span>PRIORITY</span><span>STATUS</span></div>{tasks.length?tasks.slice(-6).reverse().map(t=><div className="task-row" key={t.id}><b>{t.id}</b><span>{t.robotId||'—'}</span><span>{t.source} <ChevronRight size={12}/> Dispatch</span><em className={t.priority.toLowerCase()}>{t.priority}</em><i className={t.status.toLowerCase().replace(' ','-')}>{t.status}</i></div>):<div className="empty">No tasks yet. Start the simulation or generate a task.</div>}</div> }
function ActivityLog({logs}:{logs:Log[]}) { return <div className="panel activity-log"><PanelTitle icon={<Activity size={17}/>} title="Activity Stream"/><div className="log-list">{logs.length?logs.map((l,i)=><p key={i}><time>{l.time}</time><span className={l.type.toLowerCase().replace(' ','-')}>{l.type}</span>{l.message}</p>):<div className="empty">Telemetry stream ready.</div>}</div></div> }
function EdgePanel({robots,moving,avgBattery}:{robots:Robot[];moving:number;avgBattery:number}) { return <div className="panel edge-panel"><PanelTitle icon={<Cpu size={17}/>} title="Edge Control Center"/><div className="edge-grid"><label>FLEET <b>5/5 ONLINE</b></label><label>NETWORK <b>STABLE</b></label><label>TRAFFIC <b>{moving>2?'ELEVATED':'NORMAL'}</b></label><label>RISK <b>LOW</b></label><label>MOVING <b>{moving} AMRs</b></label><label>BATTERY <b>{avgBattery}% AVG</b></label></div><div className="health"><b>MAINTENANCE · ROBOT HEALTH</b>{robots.map(r=><span key={r.id}><i/> {r.id} NORMAL</span>)}</div></div> }
export default App
